# Tensors

In [1]:
import torch

空矩阵

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.7152e-42, 0.0000e+00],
        [0.0000e+00, 5.3530e-43, 0.0000e+00]])


 随机矩阵

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.1169, 0.6417, 0.4507],
        [0.0730, 0.4344, 0.2336],
        [0.8861, 0.3192, 0.5825],
        [0.6093, 0.8198, 0.1569],
        [0.9860, 0.1526, 0.2416]])


指定类型

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


从数据构造Tensor

In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


灵活构造Tensor

In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.0753,  0.0299,  0.2950],
        [-1.1698,  0.2945, -1.0607],
        [ 0.3418, -2.6757, -0.5896],
        [-1.1793, -0.1541,  0.6670],
        [-0.7903,  0.0201,  0.4292]])


输出尺寸

In [11]:
print(x.size())

torch.Size([5, 3])


# 操作

非原地操作

In [13]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.4286,  0.0682,  1.2893],
        [-0.2038,  0.4847, -0.6403],
        [ 0.8644, -1.8999,  0.1977],
        [-0.9931,  0.2238,  1.0575],
        [-0.0244,  0.6481,  0.8650]])


指定输出变量

In [14]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.4286,  0.0682,  1.2893],
        [-0.2038,  0.4847, -0.6403],
        [ 0.8644, -1.8999,  0.1977],
        [-0.9931,  0.2238,  1.0575],
        [-0.0244,  0.6481,  0.8650]])


加下划线，相当于 原地操作

In [15]:
y.add_(x)
print(y)

tensor([[ 1.4286,  0.0682,  1.2893],
        [-0.2038,  0.4847, -0.6403],
        [ 0.8644, -1.8999,  0.1977],
        [-0.9931,  0.2238,  1.0575],
        [-0.0244,  0.6481,  0.8650]])


切片操作跟numpy一样

In [16]:
print(x[:,1])

tensor([ 0.0299,  0.2945, -2.6757, -0.1541,  0.0201])


reshap,用torch.view

In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果一个tensor只包含了一个值，那么可以用item将其提取为python变量

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4716])
1.471578598022461


# 跟numpy之间相互转换

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


它们之间共享变量

In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu',torch.double))

tensor([2.4716], device='cuda:0')
tensor([2.4716], dtype=torch.float64)
