# 基础
torch 类 通过属性requires_grad 来指明要不要跟踪求导

使用 backward() 方法来完成自动求导，求导的值存在tensor类的 grad属性内

方法 detach() 可以阻止求导跟踪

也可以用  with torch.no_grad()

In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


因为y是操作符创建的，所以它有grad_fn属性

In [4]:
print(y.grad_fn)

In [5]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


requires_grad__()  可以改变求导属性

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


# 求导
只有标量才能求导

或者传进去一个向量

In [7]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
x = torch.randn(3,requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y=y*2
print(y)

tensor([-1552.7332,    30.2743,   777.9982], grad_fn=<MulBackward0>)


In [10]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [11]:
res = y.sum()
res.backward()
print(x.grad)

tensor([1024., 1024., 1024.])
